Deserialization
Affid/street-program pull request #3
Opened 2022-10-09 17:42 UTC by BeLIEveAl1en

2022-10-10 06:22 UTC, Affid requested changes

2022-11-08 10:45 UTC, Affid requested changes

2022-11-20 18:55 UTC, Affid requested changes

2022-11-20 18:55 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +        for (int i = 0; i < getRequiredFields().size(); i++) {
Упростить алгоритм, убрать вложенный цикл

2022-11-20 18:55 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/HumanDeserializer.java
> +        List<Pet> listOfPet = new PetDeserializer().fromJsonArray(humanMap.get("listOfPet"));
Вынеси PetDeserializer в статическую константу

2022-11-20 18:55 UTC, Affid commented on src/main/java/org/atrem/street/entities/Human.java
> +    public List<Pet> setListOfPet(List<Pet> listOfPet){
void
addPets

2022-11-20 18:55 UTC, Affid commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
>                  "\"number\": " + flat.getNumber() + ", " + "\"listOfHuman\": " + new HumanSerializer().toJsonArray(flat.getHumans()) + "}";
Доразбей строки

2023-01-18 22:17 UTC, Affid requested changes

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +    public static ArrayList<String> splitJsonArray(String arg) {
В методе splitJsonArray, условие для определения конца JSON элемента является '}' и countOfSquareBrackets == 0, но это может не работать для вложенных объектов JSON.

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +        return "{\"number\": " + flat.getNumber() + ", " + "\"listOfHuman\": " + new HumanSerializer().toJsonArray(flat.getHumans()) + "}";
Зачем каждый раз инициализировать сериалайзер, он stateless, вынеси его в константу объекта

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        jsonArray.delete(jsonArray.length() - 2, jsonArray.length());
Потенциальный баг, когда лист пуст

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/validation/JsonArrayValidator.java
> +                return true;
в ветви case 9 не происходит проверки на последующие символы после закрывающейся квадратной скобки, что может привести к неправильному результату валидации.

Иными словами, если после кейса 9 будут еще символы, текст все равно пройдет валидацию

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/validation/JsonObjectValidator.java
> +    private boolean flagOfBuf = true;
Значения переменных совершенно не ясны. Следует изменить названия или добавить комментарии

2023-01-18 22:17 UTC, Affid commented on src/main/java/org/atrem/street/validation/JsonObjectValidator.java
> +        switch (state.getState()) {
Суть кейсов считывается очень плохо, было бы хорошо заменить числа на констнты с информативными именами, либо добавить комментарии

2023-02-04 18:55 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/Parser.java
> +                case 0:
Сделал

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/Parser.java
> +    default ArrayList<HashMap<String, String>> getMapArrayFromJsonArr(String arg){
+

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/Parser.java
> +public interface Parser<T>{
+

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/PetJsonParser.java
> +public class PetJsonParser implements Parser<Pet>{
+

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/PetJsonParser.java
> +public class PetJsonParser implements Parser<Pet>{
+

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/Parser.java
> +    default HashMap<String, String> getMapFromJsonObj(String arg){
+

2023-02-04 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/PetJsonParser.java
> +
+

2023-02-04 18:57 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/PetJsonParser.java
> +        HashMap<String, String> petMap = getMapFromJsonObj(arg);
-

2023-02-04 19:06 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/PetJsonParser.java
> +        AnimalType type = AnimalType.valueOf(petMap.get("type"));
+

2023-02-04 19:07 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/PetDeserializer.java
> +        PetJsonParser petJsonParser = new PetJsonParser();
+

2023-02-04 19:07 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/HumanDeserializer.java
> +public class HumanDeserializer implements Deserializer<Human>{
+

2023-02-04 19:07 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/HumanJsonParser.java
> +        ArrayList<HashMap<String, String>> humanMapArray = getMapArrayFromJsonArr(jsonArr);
+

2023-02-04 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +        final int KEY_APPEND_STATE = 0;
+

2023-02-04 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +    T getObjFromJsonObj(String map);
+

2023-02-04 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +                    key.delete(0, key.length());
+

2023-02-04 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +public class FlatDeserializer implements Deserializer<Flat>, JsonParser<Flat> {
+

2023-02-04 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +    default ArrayList<HashMap<String, String>> getMapArrayFromJsonArr(String arg) {
+

2023-02-04 19:12 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +        ArrayList<String> jsonFlats = splitJsonArray(jsonArr);
+

2023-02-04 19:13 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +}
+

2023-02-04 19:13 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +    @Override
+

2023-02-05 18:30 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +
+

2023-02-05 18:30 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/deserialization/DeserializerTest.java
> +public class DeserializerTest {
+

2023-02-05 18:56 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/HumanDeserializer.java
> +        List<Pet> listOfPet = new PetDeserializer().fromJsonArray(humanMap.get("listOfPet"));
+

2023-02-05 19:00 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +        List<Human> humans = new HumanDeserializer().getArrayFromJsonArray(flat.get("listOfHuman"));
+

2023-02-05 19:08 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +    default void objValidator(String obj) {
+

2023-02-05 19:18 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +    default void validateFields(HashMap<String, String> map) {
+

2023-02-05 19:27 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/entities/Human.java
> +    public List<Pet> setListOfPet(List<Pet> listOfPet){
+

2023-02-05 19:27 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
>                  "\"number\": " + flat.getNumber() + ", " + "\"listOfHuman\": " + new HumanSerializer().toJsonArray(flat.getHumans()) + "}";
+

2023-02-05 19:34 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/serialization/JsonHumanDeserializerTestSerializerTest.java
> +public class JsonHumanDeserializerTestSerializerTest {
+

2023-02-05 19:34 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/serialization/JsonHumanDeserializerTestSerializerTest.java
> +public class JsonHumanDeserializerTestSerializerTest {
+

2023-02-05 19:42 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/serialization/JsonHumanDeserializerTestSerializerTest.java
> +        Serializer<Human> humanSerializerSerializer = new HumanSerializer();
+

2023-02-05 19:49 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/serialization/JsonHumanDeserializerTestSerializerTest.java
> +        String jsonPetArray = humanSerializerSerializer.toJsonArray(people);
+

2023-02-05 19:56 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/validation/JsonObjectValidatorTest.java
> +    public void shouldFailValidationOfJsonArrayValidateJsonObj(String str) {
+

2023-02-05 19:57 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/validation/JsonObjectValidatorTest.java
> +        Assertions.assertTrue(result.isValid(), String.valueOf(true));
+

2023-02-08 07:51 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +        return "{\"number\": " + flat.getNumber() + ", " + "\"listOfHuman\": " + new HumanSerializer().toJsonArray(flat.getHumans()) + "}";
+

2023-02-08 08:00 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        jsonArray.delete(jsonArray.length() - 2, jsonArray.length());
+

2023-02-10 22:25 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/validation/JsonArrayValidator.java
> +                return true;
+

2023-02-13 23:40 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/validation/JsonObjectValidator.java
> +    private boolean flagOfBuf = true;
+

2023-02-18 12:27 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +    public static ArrayList<String> splitJsonArray(String arg) {
Можно пример случая в котором данное условие будет не коректно

2023-02-21 13:32 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/serialization/JsonFlatSerializerTest.java
> +package org.atrem.street.serialization;
Как я мог бы реализовать больше ожидаемых результатов?

2023-02-25 08:46 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +
+

2023-02-25 09:39 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +        final int KEY_APPEND_STATE = 0;
+

2023-03-08 21:11 UTC, Affid requested changes

2023-03-08 21:11 UTC, Affid commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        if (array != null) {
Я бы порекомендовал это отрефакторить в 
if(array == null || array.isEmpty()){
return "[]";
}, а остальное поставить после, тогда не будет большого куска внутри ифа

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/deserialization/JsonFlatDeserializerTest.java
> +    private final FlatDeserializer FLAT_DESERIALIZER = new FlatDeserializer();
Аналогично про нейминг переменной

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/deserialization/JsonFlatDeserializerTest.java
> +        String expectedJSON = "";
Перепиши это, пожалуйста, с использованием Path API

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/deserialization/JsonFlatDeserializerTest.java
> +        String serializedFlat = getJSON("C:\\java\\programs\\street-program\\src\\test\\resources\\flat.json");
Пути должны быть относительными - с абсолютными путями эти файлы не будут найдены нигде, кроме твоего компьютера

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/serialization/JsonHumanSerializerTest.java
> +        try (FileReader reader = new FileReader(file)) {
Аналогично Path API

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/validation/JsonArrayValidatorTest.java
> +    private final String FLAT_LIST = "[{\"number\": 1, \"listOfHuman\": " + HUMAN_LIST + "},{\"number\": 2, \"listOfHuman\": " + HUMAN_LIST + "}]";
Поменяй нейминг на камел кейс, это же не статическая константа у тебя

2023-03-08 21:11 UTC, Affid commented on src/test/java/org/atrem/street/validation/JsonObjectValidatorTest.java
> +        Assertions.assertFalse(result.isValid(), "true2");
Объясни, пожалуйста, зачем вообще ты передаешь какие строки здесь вторым аргументом?

2023-03-08 21:22 UTC, Affid commented on src/main/java/org/atrem/street/jsonParser/JsonParser.java
> +    public static ArrayList<String> splitJsonArray(String arg) {
``` json
[{"xyz":{...}}, {...}, {...}]
```


Здесь мы видим, что у первого объекта в массиве есть вложенный объект по ключу 'xyz'. 
Если я правильно помню, то крайние [] ты отбрасываешь.

Тогда чтение первого объекта завершится на } вложенного этого вложенного объекта.

Однако боюсь, мы слишком закопаемся в подробности чтения json, так что давай эту часть оставим, как есть уже

2023-04-13 08:51 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        if (array != null) {
А почему оставлять большой кусок кода в if это плохо?

2023-04-13 20:49 UTC, Affid commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        if (array != null) {
Потому что это повышает так называемую когнитивную сложность кода. Чем больше вложенного кода, тем сложнее его читать - потому что нужно держать в голове все условия выполнения этого кода

По возможности желательно держать код настолько плоским, насколько возможно

2023-04-15 12:32 UTC, BeLIEveAl1en commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +        return jsonArray.toString().replaceAll("\\s", "");
Изначально в файлах из которых я беру людей, животных и т.д. имеют пробелы и поэтому я их убираю

2023-04-16 08:17 UTC, Affid commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +        return jsonArray.toString().replaceAll("\\s", "");
Файлы, откуда ты берешь данные, записываются тобой же через эту программу. То есть формат должен быть одним и тем же - и если тебе мешают пробелы между запятыми, например, ты можешь убедиться, что при сохранении эти пробелы не ставятся тобой дополнительно к данным. Когда ты удаляешь пробелы, ты меняешь сами данные, которые были сохранены. Пример, который я привел выше, это иллюстрирует - у питомца было имя "Снежок Второй", но после того, как ты сохранишь это в файл и считаешь обратно, оно поменяется на "СнежокВторой". Это как если бы в ВК ты ввел свое имя, а после перезагрузки страницы получил бы АртемМоргун

2023-04-16 14:26 UTC, Affid requested changes

2023-04-16 14:26 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/Deserializer.java
> +    default void validate_obj(String obj) {
Артем, ты используешь не Java код стайл. Посмотри, пожалуйста, какая конвенция для именования методов, и поправь нейминг здесь и далее

2023-04-16 14:26 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +    private final HumanDeserializer human_deserializer = new HumanDeserializer();
Здесь почти правильно, но не забывай, что у констант мы используем upper case, а не lower case

2023-04-16 14:26 UTC, Affid commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +            jsonArray.append(toJsonObject(flat)).append(", ");
Для чего ты ставишь здесь пробел, если потом сам же эти пробелы убираешь?
Возможно, стоит не ставить пробелы при сериализации, так как они тебе не нужны

2023-04-16 14:26 UTC, Affid commented on src/main/java/org/atrem/street/serialization/HumanSerializer.java
> +        return "{\"name\":" + "\"" + obj.getName() + "\",\"lastName\":" + "\"" + obj.getLastName() + "\",\"money\":" + obj.getMoney() + ",\"listOfPet\":" + pet_serializer.toJsonArray(obj.getListOfPet
Я бы предложил здесь и в аналогичных местах использовать форматные строки вместо такого рода конкатенации. Шаблон форматной строки можно положить в константу, а здесь вызывать String.format и передавать нужные аргументы

2023-04-16 14:26 UTC, Affid commented on src/test/java/org/atrem/street/jsonParser/JsonPaserTest.java
>          Assertions.assertEquals(expected, result);
Не рекомендую оставлять закомментированный код без очень веских причин. Почему здесь ты оставил его закомментированным?

2023-04-20 21:52 UTC, BeLIEveAl1en commented on src/test/java/org/atrem/street/jsonParser/JsonPaserTest.java
>          Assertions.assertEquals(expected, result);
Я хотел показать, что парсер не может работать с работать с простыми объектами. Я хотел поправить это потом

2023-04-22 10:33 UTC, Affid commented on src/test/java/org/atrem/street/jsonParser/JsonPaserTest.java
>          Assertions.assertEquals(expected, result);
Я думаю, мы не будем дальше уже сильно использовать это, чтобы избежать переусложнения программы, так что можно удалить этот тест смело

2023-04-30 10:08 UTC, Affid requested changes

2023-04-30 10:08 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/FlatDeserializer.java
> +    private final HumanDeserializer HUMAN_DESERIALIZER = new HumanDeserializer();
Почти
Артем, но ты все еще неправильный нейминг используешь.

Это не статическая константа у тебя, поэтому upper snake case тут не применим. 

Так что тут 2 пути - сделай поле статическим, либо поменяй нейминг. 

Если это стейтлесс объект, то можно спокойно сделать статическим.

Выглядит так, будто у тебя образовался серьезный пробел в правилах нейминга, перечитай пожалуйста правила нейминга для Java.

https://google.github.io/styleguide/javaguide.html#s5-naming
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-04-30 10:08 UTC, Affid commented on src/main/java/org/atrem/street/serialization/FlatSerializer.java
> +    private final String asd = "{\"number\":%s," + "\"listOfHuman\":%s}";
Что значит asd???

2023-04-30 10:08 UTC, Affid commented on src/main/java/org/atrem/street/serialization/HouseSerializer.java
> +        return String.format(FORMAT_STRING, obj.getNumber(), FlAT_DESERIALIZER.toJsonArray(obj.getListOfFlats()));
FORMAT_STRING не несет никакой информации, так как это первый аргумент метода format, и так понятно, что это форматная строка. Условный HOUSE_TEMPLATE нес бы больше информации для читающего

2023-05-30 16:48 UTC, Affid commented on src/main/java/org/atrem/street/deserialization/HouseDeserializer.java
> +    private static final FlatDeserializer FlAT_DESERIALIZER = new FlatDeserializer();
Игра "Найди маленькую букву среди больших"...)

2023-06-01 16:29 UTC, merged